apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    nodePort: 30000
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: init-db-config-map
          configMap:
            name: db-init
      containers:
        - name: postgres
          image: postgres:9
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-db-config-map
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
data:
  init.sql: |
    CREATE DATABASE "pearl-wallet"
  #Aqui podrian ir todos los create, insert, etc
  #Pero sale mejor en este caso solo crear la base e importar desde dbeaver
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
#password encoded en base64 en este caso es "admin" = "YWRtaW4="
  password: YWRtaW4=
type: Opaque
#Para probar si funciona ejectar
#kubectl port-forward deployment/postgres 8888:5432 ; 8888 = puede ser cualquier puerto pero por comodidad se usa este
#y tratar de conectar en dbeaver con user: localhost en port: 8888 pass: admin
#ya connectado puedo hacer restore de mi base de datos
#no es necesario hacer el script