apiVersion: v1
kind: Service
metadata:
  name: pearl-wallet-fe
spec:
  type: NodePort
  selector:
    app: pearl-wallet-fe
  ports:
  - port: 80
    nodePort: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearl-wallet-fe
spec:
  selector:
    matchLabels:
      app: pearl-wallet-fe
  template:
    metadata:
      labels:
        app: pearl-wallet-fe
    spec:
      containers:
      - name: pearl-wallet-fe
        image: ojcl/pearl-wallet:fe-0.1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
#Para probar si funciona ejecutar
#kubectl port-forward services/pearl-wallet-fe 8888:80 -n default